services:
  - type: web
    name: fake-news-detector-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn --chdir backend --worker-class gevent --workers 2 --threads 4 --timeout 120 app:app
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: RENDER_EXTERNAL_URL
        sync: true  # âœ… so auto-ping works using your Render URL
      - key: HUGGINGFACE_HUB_TOKEN
        sync: false
