services:
  - type: web
    name: fake-news-detector-api
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PORT
        value: 10000
